services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true

  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    environment:
      DB_URL: "host=db port=5432 user=dawn_user password=dawn_password dbname=dawn_db sslmode=disable"

  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: dawn_user
      POSTGRES_PASSWORD: dawn_password
      POSTGRES_DB: dawn_db
      POSTGRES_PORT: 5432
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

